import { ROLES } from './roles';
import { PERMISSIONS } from './permissions';

export const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),

  [ROLES.PRODUCT_INVENTORY_MANAGER]: [
    PERMISSIONS.PRODUCTS_VIEW,
    PERMISSIONS.PRODUCTS_CREATE,
    PERMISSIONS.PRODUCTS_EDIT,
    PERMISSIONS.PRODUCTS_DELETE,
    PERMISSIONS.CATEGORIES_VIEW,
    PERMISSIONS.CATEGORIES_MANAGE,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_UPDATE,
    PERMISSIONS.INVENTORY_ADJUST,
    PERMISSIONS.ACTIVITY_LOGS_VIEW_SCOPED
  ],

  [ROLES.ORDER_MANAGER]: [
    PERMISSIONS.ORDERS_VIEW,
    PERMISSIONS.ORDERS_PROCESS,
    PERMISSIONS.ORDERS_UPDATE_STATUS,
    PERMISSIONS.SHIPMENTS_VIEW,
    PERMISSIONS.SHIPMENTS_UPDATE,
    PERMISSIONS.RETURNS_VIEW,
    PERMISSIONS.RETURNS_PROCESS,
    PERMISSIONS.REFUNDS_VIEW,
    PERMISSIONS.REFUNDS_PROCESS,
    PERMISSIONS.ACTIVITY_LOGS_VIEW_SCOPED
  ],

  [ROLES.CUSTOMER_SUPPORT_EXECUTIVE]: [
    PERMISSIONS.SUPPORT_VIEW,
    PERMISSIONS.SUPPORT_REPLY,
    PERMISSIONS.SUPPORT_UPDATE,
    PERMISSIONS.SUPPORT_ASSIGN,
    PERMISSIONS.ORDERS_VIEW,     // Read-only customer resolution
    PERMISSIONS.SHIPMENTS_VIEW,  // Read-only customer resolution
    PERMISSIONS.CUSTOMERS_VIEW,  // Read-only customer resolution
    PERMISSIONS.ACTIVITY_LOGS_VIEW_SCOPED
  ],

  [ROLES.MARKETING_MANAGER]: [
    PERMISSIONS.COUPONS_VIEW,
    PERMISSIONS.COUPONS_CREATE,
    PERMISSIONS.COUPONS_EDIT,
    PERMISSIONS.COUPONS_ACTIVATE,
    PERMISSIONS.REVIEWS_VIEW,
    PERMISSIONS.REVIEWS_MODERATE,
    PERMISSIONS.ACTIVITY_LOGS_VIEW_SCOPED
  ],

  [ROLES.FINANCE_MANAGER]: [
    PERMISSIONS.PAYMENTS_VIEW,
    PERMISSIONS.PAYMENTS_PROCESS,
    PERMISSIONS.FINANCE_REPORTS,
    PERMISSIONS.REFUNDS_VIEW,
    PERMISSIONS.REFUNDS_PROCESS,
    PERMISSIONS.ACTIVITY_LOGS_VIEW_SCOPED
  ]
};